"""Conductor 内置工具"""

from .memory_ops import (
    VIEW_MEMORY_TOOL,
    ADD_MEMORY_TOOL,
    SEARCH_MEMORY_TOOL,
    DELETE_MEMORY_TOOL,
    CLEAR_MEMORY_BY_CATEGORY_TOOL,
    CLEAR_ALL_MEMORY_TOOL
)
from .status_ops import (
    GET_AGENT_STATUS_TOOL,
    LIST_AGENTS_TOOL
)
from .feedback_ops import GET_USER_FEEDBACK_TOOL
from .sub_agent_ops import CALL_SUB_AGENT_TOOL, GET_SUB_AGENT_STATUS_TOOL
from .file_ops import (
    LIST_DIRECTORY_TOOL,
    READ_TEXT_FILE_TOOL,
    VIEW_IMAGE_TOOL,
    OPEN_WITH_PLAYER_TOOL,
    COPY_FILE_TOOL,
    MOVE_FILE_TOOL,
    DELETE_FILE_TOOL
)


CONDUCTOR_BUILTIN_TOOLS = [
    # 记忆操作
    VIEW_MEMORY_TOOL,
    ADD_MEMORY_TOOL,
    SEARCH_MEMORY_TOOL,
    DELETE_MEMORY_TOOL,
    CLEAR_MEMORY_BY_CATEGORY_TOOL,
    CLEAR_ALL_MEMORY_TOOL,
    # Agent 状态
    GET_AGENT_STATUS_TOOL,
    LIST_AGENTS_TOOL,
    # 子 Agent 调用
    CALL_SUB_AGENT_TOOL,
    GET_SUB_AGENT_STATUS_TOOL,
    # 反馈
    GET_USER_FEEDBACK_TOOL,
    # 文件操作
    LIST_DIRECTORY_TOOL,
    READ_TEXT_FILE_TOOL,
    VIEW_IMAGE_TOOL,
    OPEN_WITH_PLAYER_TOOL,
    COPY_FILE_TOOL,
    MOVE_FILE_TOOL,
    DELETE_FILE_TOOL,
]