"""Creator 内置工具"""

from .memory_ops import (
    VIEW_MEMORY_TOOL,
    ADD_MEMORY_TOOL,
    SEARCH_MEMORY_TOOL,
    DELETE_MEMORY_TOOL,
    CLEAR_MEMORY_BY_CATEGORY_TOOL,
    CLEAR_ALL_MEMORY_TOOL
)
from .image_gen import (
    GENERATE_IMAGE_TOOL,
    GENERATE_IMAGE_WITH_REFERENCE_TOOL
)
from .rag_manager import (
    ADD_RAG_RECORD_TOOL,
    LIST_RAG_CATEGORIES_TOOL,
    VIEW_RAG_RECORDS_TOOL,
    CLEAR_RAG_CATEGORY_TOOL,
    SEARCH_RAG_TOOL
)

CREATOR_BUILTIN_TOOLS = [
    # 记忆操作
    VIEW_MEMORY_TOOL,
    ADD_MEMORY_TOOL,
    SEARCH_MEMORY_TOOL,
    DELETE_MEMORY_TOOL,
    CLEAR_MEMORY_BY_CATEGORY_TOOL,
    CLEAR_ALL_MEMORY_TOOL,
    # 图片生成
    GENERATE_IMAGE_TOOL,
    GENERATE_IMAGE_WITH_REFERENCE_TOOL,
    # RAG 管理
    ADD_RAG_RECORD_TOOL,
    LIST_RAG_CATEGORIES_TOOL,
    VIEW_RAG_RECORDS_TOOL,
    CLEAR_RAG_CATEGORY_TOOL,
    SEARCH_RAG_TOOL 
]