"""engineer 内置工具"""

from .memory_ops import (
    VIEW_MEMORY_TOOL,
    ADD_MEMORY_TOOL,
    SEARCH_MEMORY_TOOL,
    DELETE_MEMORY_TOOL,
    CLEAR_MEMORY_BY_CATEGORY_TOOL,
    CLEAR_ALL_MEMORY_TOOL
)

from .rag_manager import (
    ADD_RAG_RECORD_TOOL,
    LIST_RAG_CATEGORIES_TOOL,
    VIEW_RAG_RECORDS_TOOL,
    CLEAR_RAG_CATEGORY_TOOL,
    SEARCH_RAG_TOOL
)


from .error_fixer import (
    DIAGNOSE_ERROR_TOOL,
    RECORD_TREATMENT_TOOL
)

from .claude_code import (
    CLAUDE_READ_TOOL,
    CLAUDE_WRITE_TOOL,
    CLAUDE_EDIT_TOOL,
    CLAUDE_MULTI_EDIT_TOOL,
    CLAUDE_GREP_TOOL,
    CLAUDE_DIRECTORY_TREE_TOOL,
    CLAUDE_RUN_COMMAND_TOOL,
    CLAUDE_CONTENT_REPLACE_TOOL,
    CLAUDE_THINK_TOOL,
    CLAUDE_TODO_WRITE_TOOL,
    CLAUDE_TODO_READ_TOOL,
    CLAUDE_BATCH_TOOL
)


ENGINEER_BUILTIN_TOOLS = [
    # 记忆操作
    VIEW_MEMORY_TOOL,
    ADD_MEMORY_TOOL,
    SEARCH_MEMORY_TOOL,
    DELETE_MEMORY_TOOL,
    CLEAR_MEMORY_BY_CATEGORY_TOOL,
    CLEAR_ALL_MEMORY_TOOL,
    # RAG 管理
    ADD_RAG_RECORD_TOOL,
    LIST_RAG_CATEGORIES_TOOL,
    VIEW_RAG_RECORDS_TOOL,
    CLEAR_RAG_CATEGORY_TOOL,
    SEARCH_RAG_TOOL,
    # 错误诊断
    DIAGNOSE_ERROR_TOOL,
    RECORD_TREATMENT_TOOL,
    # ClaudeCode 本地工具（绕过 MCP）
    CLAUDE_READ_TOOL,
    CLAUDE_WRITE_TOOL,
    CLAUDE_EDIT_TOOL,
    CLAUDE_MULTI_EDIT_TOOL,
    CLAUDE_GREP_TOOL,
    CLAUDE_DIRECTORY_TREE_TOOL,
    CLAUDE_RUN_COMMAND_TOOL,
    CLAUDE_CONTENT_REPLACE_TOOL,
    CLAUDE_THINK_TOOL,
    CLAUDE_TODO_WRITE_TOOL,
    CLAUDE_TODO_READ_TOOL,
    CLAUDE_BATCH_TOOL,
]